
main: main.o datos.o calculos.o
    -o main main.o datos.o calculos.o

main.o: main.c datos.h calculos.h
    -c main.c

datos.o: datos.c datos.h
    -c datos.c

calculos.o: calculos.c calculos.h
    -c calculos.c

clean:
	rm -f *.o *.s main
